### YamlMime:ManagedReference
items:
- uid: Application.Interfaces.Services.Hub.IManagerStartMatchService
  commentId: T:Application.Interfaces.Services.Hub.IManagerStartMatchService
  id: IManagerStartMatchService
  parent: Application.Interfaces.Services.Hub
  children:
  - Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync(System.Nullable{System.Guid},System.Nullable{System.Guid},System.String)
  - Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync(System.Guid,System.String,System.Guid,System.String)
  - Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync(System.Guid,System.Guid,System.String)
  langs:
  - csharp
  - vb
  name: IManagerStartMatchService
  nameWithType: IManagerStartMatchService
  fullName: Application.Interfaces.Services.Hub.IManagerStartMatchService
  type: Interface
  source:
    remote:
      path: Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: IManagerStartMatchService
    path: ../Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
    startLine: 4
  assemblies:
  - Application
  namespace: Application.Interfaces.Services.Hub
  syntax:
    content: public interface IManagerStartMatchService
    content.vb: Public Interface IManagerStartMatchService
- uid: Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync(System.Guid,System.String,System.Guid,System.String)
  commentId: M:Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync(System.Guid,System.String,System.Guid,System.String)
  id: JoinHubAsync(System.Guid,System.String,System.Guid,System.String)
  parent: Application.Interfaces.Services.Hub.IManagerStartMatchService
  langs:
  - csharp
  - vb
  name: JoinHubAsync(Guid, string, Guid, string)
  nameWithType: IManagerStartMatchService.JoinHubAsync(Guid, string, Guid, string)
  fullName: Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync(System.Guid, string, System.Guid, string)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: JoinHubAsync
    path: ../Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Interfaces.Services.Hub
  syntax:
    content: Task<JoinStartMatchResult> JoinHubAsync(Guid matchId, string userId, Guid idTeam, string connectionId)
    parameters:
    - id: matchId
      type: System.Guid
    - id: userId
      type: System.String
    - id: idTeam
      type: System.Guid
    - id: connectionId
      type: System.String
    return:
      type: System.Threading.Tasks.Task{Application.Hubs.JoinStartMatchResult}
    content.vb: Function JoinHubAsync(matchId As Guid, userId As String, idTeam As Guid, connectionId As String) As Task(Of JoinStartMatchResult)
  overload: Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync*
  nameWithType.vb: IManagerStartMatchService.JoinHubAsync(Guid, String, Guid, String)
  fullName.vb: Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync(System.Guid, String, System.Guid, String)
  name.vb: JoinHubAsync(Guid, String, Guid, String)
- uid: Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync(System.Guid,System.Guid,System.String)
  commentId: M:Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync(System.Guid,System.Guid,System.String)
  id: LeaveHubAsync(System.Guid,System.Guid,System.String)
  parent: Application.Interfaces.Services.Hub.IManagerStartMatchService
  langs:
  - csharp
  - vb
  name: LeaveHubAsync(Guid, Guid, string)
  nameWithType: IManagerStartMatchService.LeaveHubAsync(Guid, Guid, string)
  fullName: Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync(System.Guid, System.Guid, string)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: LeaveHubAsync
    path: ../Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Interfaces.Services.Hub
  syntax:
    content: Task<bool> LeaveHubAsync(Guid matchId, Guid idTeam, string connectionId)
    parameters:
    - id: matchId
      type: System.Guid
    - id: idTeam
      type: System.Guid
    - id: connectionId
      type: System.String
    return:
      type: System.Threading.Tasks.Task{System.Boolean}
    content.vb: Function LeaveHubAsync(matchId As Guid, idTeam As Guid, connectionId As String) As Task(Of Boolean)
  overload: Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync*
  nameWithType.vb: IManagerStartMatchService.LeaveHubAsync(Guid, Guid, String)
  fullName.vb: Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync(System.Guid, System.Guid, String)
  name.vb: LeaveHubAsync(Guid, Guid, String)
- uid: Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync(System.Nullable{System.Guid},System.Nullable{System.Guid},System.String)
  commentId: M:Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync(System.Nullable{System.Guid},System.Nullable{System.Guid},System.String)
  id: HandleDisconnectAsync(System.Nullable{System.Guid},System.Nullable{System.Guid},System.String)
  parent: Application.Interfaces.Services.Hub.IManagerStartMatchService
  langs:
  - csharp
  - vb
  name: HandleDisconnectAsync(Guid?, Guid?, string)
  nameWithType: IManagerStartMatchService.HandleDisconnectAsync(Guid?, Guid?, string)
  fullName: Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync(System.Guid?, System.Guid?, string)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: HandleDisconnectAsync
    path: ../Application/Interfaces/Services/Hub/IManagerStartMatchService.cs
    startLine: 8
  assemblies:
  - Application
  namespace: Application.Interfaces.Services.Hub
  syntax:
    content: Task<bool> HandleDisconnectAsync(Guid? maybeMatchId, Guid? maybeTeamId, string connectionId)
    parameters:
    - id: maybeMatchId
      type: System.Nullable{System.Guid}
    - id: maybeTeamId
      type: System.Nullable{System.Guid}
    - id: connectionId
      type: System.String
    return:
      type: System.Threading.Tasks.Task{System.Boolean}
    content.vb: Function HandleDisconnectAsync(maybeMatchId As Guid?, maybeTeamId As Guid?, connectionId As String) As Task(Of Boolean)
  overload: Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync*
  nameWithType.vb: IManagerStartMatchService.HandleDisconnectAsync(Guid?, Guid?, String)
  fullName.vb: Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync(System.Guid?, System.Guid?, String)
  name.vb: HandleDisconnectAsync(Guid?, Guid?, String)
references:
- uid: Application.Interfaces.Services.Hub
  commentId: N:Application.Interfaces.Services.Hub
  href: Application.html
  name: Application.Interfaces.Services.Hub
  nameWithType: Application.Interfaces.Services.Hub
  fullName: Application.Interfaces.Services.Hub
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Services
    name: Services
    href: Application.Interfaces.Services.html
  - name: .
  - uid: Application.Interfaces.Services.Hub
    name: Hub
    href: Application.Interfaces.Services.Hub.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Services
    name: Services
    href: Application.Interfaces.Services.html
  - name: .
  - uid: Application.Interfaces.Services.Hub
    name: Hub
    href: Application.Interfaces.Services.Hub.html
- uid: Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync*
  commentId: Overload:Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync
  href: Application.Interfaces.Services.Hub.IManagerStartMatchService.html#Application_Interfaces_Services_Hub_IManagerStartMatchService_JoinHubAsync_System_Guid_System_String_System_Guid_System_String_
  name: JoinHubAsync
  nameWithType: IManagerStartMatchService.JoinHubAsync
  fullName: Application.Interfaces.Services.Hub.IManagerStartMatchService.JoinHubAsync
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Threading.Tasks.Task{Application.Hubs.JoinStartMatchResult}
  commentId: T:System.Threading.Tasks.Task{Application.Hubs.JoinStartMatchResult}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<JoinStartMatchResult>
  nameWithType: Task<JoinStartMatchResult>
  fullName: System.Threading.Tasks.Task<Application.Hubs.JoinStartMatchResult>
  nameWithType.vb: Task(Of JoinStartMatchResult)
  fullName.vb: System.Threading.Tasks.Task(Of Application.Hubs.JoinStartMatchResult)
  name.vb: Task(Of JoinStartMatchResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: Application.Hubs.JoinStartMatchResult
    name: JoinStartMatchResult
    href: Application.Hubs.JoinStartMatchResult.html
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: Application.Hubs.JoinStartMatchResult
    name: JoinStartMatchResult
    href: Application.Hubs.JoinStartMatchResult.html
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync*
  commentId: Overload:Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync
  href: Application.Interfaces.Services.Hub.IManagerStartMatchService.html#Application_Interfaces_Services_Hub_IManagerStartMatchService_LeaveHubAsync_System_Guid_System_Guid_System_String_
  name: LeaveHubAsync
  nameWithType: IManagerStartMatchService.LeaveHubAsync
  fullName: Application.Interfaces.Services.Hub.IManagerStartMatchService.LeaveHubAsync
- uid: System.Threading.Tasks.Task{System.Boolean}
  commentId: T:System.Threading.Tasks.Task{System.Boolean}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<bool>
  nameWithType: Task<bool>
  fullName: System.Threading.Tasks.Task<bool>
  nameWithType.vb: Task(Of Boolean)
  fullName.vb: System.Threading.Tasks.Task(Of Boolean)
  name.vb: Task(Of Boolean)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync*
  commentId: Overload:Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync
  href: Application.Interfaces.Services.Hub.IManagerStartMatchService.html#Application_Interfaces_Services_Hub_IManagerStartMatchService_HandleDisconnectAsync_System_Nullable_System_Guid__System_Nullable_System_Guid__System_String_
  name: HandleDisconnectAsync
  nameWithType: IManagerStartMatchService.HandleDisconnectAsync
  fullName: Application.Interfaces.Services.Hub.IManagerStartMatchService.HandleDisconnectAsync
- uid: System.Nullable{System.Guid}
  commentId: T:System.Nullable{System.Guid}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid?
  nameWithType: Guid?
  fullName: System.Guid?
  spec.csharp:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
  spec.vb:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
