### YamlMime:ManagedReference
items:
- uid: Application.Interfaces.Repositories.ITeamStatisticsRepository
  commentId: T:Application.Interfaces.Repositories.ITeamStatisticsRepository
  id: ITeamStatisticsRepository
  parent: Application.Interfaces.Repositories
  children:
  - Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics(Domain.Entities.TeamStatistics)
  - Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch(System.Guid,System.Guid)
  langs:
  - csharp
  - vb
  name: ITeamStatisticsRepository
  nameWithType: ITeamStatisticsRepository
  fullName: Application.Interfaces.Repositories.ITeamStatisticsRepository
  type: Interface
  source:
    remote:
      path: Application/Interfaces/Repositories/ITeamStatisticsRepository.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: ITeamStatisticsRepository
    path: ../Application/Interfaces/Repositories/ITeamStatisticsRepository.cs
    startLine: 4
  assemblies:
  - Application
  namespace: Application.Interfaces.Repositories
  syntax:
    content: public interface ITeamStatisticsRepository
    content.vb: Public Interface ITeamStatisticsRepository
- uid: Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics(Domain.Entities.TeamStatistics)
  commentId: M:Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics(Domain.Entities.TeamStatistics)
  id: AddTeamStatistics(Domain.Entities.TeamStatistics)
  parent: Application.Interfaces.Repositories.ITeamStatisticsRepository
  langs:
  - csharp
  - vb
  name: AddTeamStatistics(TeamStatistics)
  nameWithType: ITeamStatisticsRepository.AddTeamStatistics(TeamStatistics)
  fullName: Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics(Domain.Entities.TeamStatistics)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Repositories/ITeamStatisticsRepository.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: AddTeamStatistics
    path: ../Application/Interfaces/Repositories/ITeamStatisticsRepository.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Interfaces.Repositories
  syntax:
    content: Task AddTeamStatistics(TeamStatistics teamStatistics)
    parameters:
    - id: teamStatistics
      type: Domain.Entities.TeamStatistics
    return:
      type: System.Threading.Tasks.Task
    content.vb: Function AddTeamStatistics(teamStatistics As TeamStatistics) As Task
  overload: Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics*
- uid: Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch(System.Guid,System.Guid)
  commentId: M:Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch(System.Guid,System.Guid)
  id: GetTeamByIdAndMatch(System.Guid,System.Guid)
  parent: Application.Interfaces.Repositories.ITeamStatisticsRepository
  langs:
  - csharp
  - vb
  name: GetTeamByIdAndMatch(Guid, Guid)
  nameWithType: ITeamStatisticsRepository.GetTeamByIdAndMatch(Guid, Guid)
  fullName: Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch(System.Guid, System.Guid)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Repositories/ITeamStatisticsRepository.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: GetTeamByIdAndMatch
    path: ../Application/Interfaces/Repositories/ITeamStatisticsRepository.cs
    startLine: 8
  assemblies:
  - Application
  namespace: Application.Interfaces.Repositories
  syntax:
    content: Task<TeamStatistics> GetTeamByIdAndMatch(Guid idMatch, Guid idTeam)
    parameters:
    - id: idMatch
      type: System.Guid
    - id: idTeam
      type: System.Guid
    return:
      type: System.Threading.Tasks.Task{Domain.Entities.TeamStatistics}
    content.vb: Function GetTeamByIdAndMatch(idMatch As Guid, idTeam As Guid) As Task(Of TeamStatistics)
  overload: Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch*
references:
- uid: Application.Interfaces.Repositories
  commentId: N:Application.Interfaces.Repositories
  href: Application.html
  name: Application.Interfaces.Repositories
  nameWithType: Application.Interfaces.Repositories
  fullName: Application.Interfaces.Repositories
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Repositories
    name: Repositories
    href: Application.Interfaces.Repositories.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Repositories
    name: Repositories
    href: Application.Interfaces.Repositories.html
- uid: Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics*
  commentId: Overload:Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics
  href: Application.Interfaces.Repositories.ITeamStatisticsRepository.html#Application_Interfaces_Repositories_ITeamStatisticsRepository_AddTeamStatistics_Domain_Entities_TeamStatistics_
  name: AddTeamStatistics
  nameWithType: ITeamStatisticsRepository.AddTeamStatistics
  fullName: Application.Interfaces.Repositories.ITeamStatisticsRepository.AddTeamStatistics
- uid: Domain.Entities.TeamStatistics
  commentId: T:Domain.Entities.TeamStatistics
  parent: Domain.Entities
  href: Domain.Entities.TeamStatistics.html
  name: TeamStatistics
  nameWithType: TeamStatistics
  fullName: Domain.Entities.TeamStatistics
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: Domain.Entities
  commentId: N:Domain.Entities
  href: Domain.html
  name: Domain.Entities
  nameWithType: Domain.Entities
  fullName: Domain.Entities
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Entities
    name: Entities
    href: Domain.Entities.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Entities
    name: Entities
    href: Domain.Entities.html
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch*
  commentId: Overload:Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch
  href: Application.Interfaces.Repositories.ITeamStatisticsRepository.html#Application_Interfaces_Repositories_ITeamStatisticsRepository_GetTeamByIdAndMatch_System_Guid_System_Guid_
  name: GetTeamByIdAndMatch
  nameWithType: ITeamStatisticsRepository.GetTeamByIdAndMatch
  fullName: Application.Interfaces.Repositories.ITeamStatisticsRepository.GetTeamByIdAndMatch
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Threading.Tasks.Task{Domain.Entities.TeamStatistics}
  commentId: T:System.Threading.Tasks.Task{Domain.Entities.TeamStatistics}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TeamStatistics>
  nameWithType: Task<TeamStatistics>
  fullName: System.Threading.Tasks.Task<Domain.Entities.TeamStatistics>
  nameWithType.vb: Task(Of TeamStatistics)
  fullName.vb: System.Threading.Tasks.Task(Of Domain.Entities.TeamStatistics)
  name.vb: Task(Of TeamStatistics)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: Domain.Entities.TeamStatistics
    name: TeamStatistics
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: Domain.Entities.TeamStatistics
    name: TeamStatistics
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
