### YamlMime:ManagedReference
items:
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto
  commentId: T:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto
  id: AcceptRefusePostPoneDto
  parent: Application.DTOs.PostPoneGame
  children:
  - Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch
  - Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent
  - Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam
  - Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone
  langs:
  - csharp
  - vb
  name: AcceptRefusePostPoneDto
  nameWithType: AcceptRefusePostPoneDto
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto
  type: Class
  source:
    remote:
      path: Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: AcceptRefusePostPoneDto
    path: ../Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.DTOs.PostPoneGame
  syntax:
    content: public class AcceptRefusePostPoneDto
    content.vb: Public Class AcceptRefusePostPoneDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch
  commentId: P:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch
  id: IdMatch
  parent: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto
  langs:
  - csharp
  - vb
  name: IdMatch
  nameWithType: AcceptRefusePostPoneDto.IdMatch
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch
  type: Property
  source:
    remote:
      path: Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: IdMatch
    path: ../Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.DTOs.PostPoneGame
  syntax:
    content: >-
      [Required(ErrorMessage = "O id da partida tem de estar preenchido")]

      public Guid IdMatch { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: >-
      <Required(ErrorMessage:="O id da partida tem de estar preenchido")>

      Public Property IdMatch As Guid
  overload: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: O id da partida tem de estar preenchido
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone
  commentId: P:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone
  id: StatusPostPone
  parent: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto
  langs:
  - csharp
  - vb
  name: StatusPostPone
  nameWithType: AcceptRefusePostPoneDto.StatusPostPone
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone
  type: Property
  source:
    remote:
      path: Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: StatusPostPone
    path: ../Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
    startLine: 10
  assemblies:
  - Application
  namespace: Application.DTOs.PostPoneGame
  syntax:
    content: >-
      [Required(ErrorMessage = "Tem de estar especificado o estado do PostPone")]

      public StatusPostPone StatusPostPone { get; set; }
    parameters: []
    return:
      type: Domain.Enums.StatusPostPone
    content.vb: >-
      <Required(ErrorMessage:="Tem de estar especificado o estado do PostPone")>

      Public Property StatusPostPone As StatusPostPone
  overload: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: Tem de estar especificado o estado do PostPone
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam
  commentId: P:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam
  id: IdTeam
  parent: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto
  langs:
  - csharp
  - vb
  name: IdTeam
  nameWithType: AcceptRefusePostPoneDto.IdTeam
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam
  type: Property
  source:
    remote:
      path: Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: IdTeam
    path: ../Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
    startLine: 13
  assemblies:
  - Application
  namespace: Application.DTOs.PostPoneGame
  syntax:
    content: >-
      [Required(ErrorMessage = "O id da equipa tem de estar preenchido")]

      public Guid IdTeam { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: >-
      <Required(ErrorMessage:="O id da equipa tem de estar preenchido")>

      Public Property IdTeam As Guid
  overload: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: O id da equipa tem de estar preenchido
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent
  commentId: P:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent
  id: IdOpponent
  parent: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto
  langs:
  - csharp
  - vb
  name: IdOpponent
  nameWithType: AcceptRefusePostPoneDto.IdOpponent
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent
  type: Property
  source:
    remote:
      path: Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: IdOpponent
    path: ../Application/DTOs/PostPoneGame/AcceptRefusePostPoneDTO.cs
    startLine: 16
  assemblies:
  - Application
  namespace: Application.DTOs.PostPoneGame
  syntax:
    content: >-
      [Required(ErrorMessage = "O id do opponente tem de estar preenchido")]

      public Guid IdOpponent { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: >-
      <Required(ErrorMessage:="O id do opponente tem de estar preenchido")>

      Public Property IdOpponent As Guid
  overload: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: O id do opponente tem de estar preenchido
references:
- uid: Application.DTOs.PostPoneGame
  commentId: N:Application.DTOs.PostPoneGame
  href: Application.html
  name: Application.DTOs.PostPoneGame
  nameWithType: Application.DTOs.PostPoneGame
  fullName: Application.DTOs.PostPoneGame
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.DTOs
    name: DTOs
    href: Application.DTOs.html
  - name: .
  - uid: Application.DTOs.PostPoneGame
    name: PostPoneGame
    href: Application.DTOs.PostPoneGame.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.DTOs
    name: DTOs
    href: Application.DTOs.html
  - name: .
  - uid: Application.DTOs.PostPoneGame
    name: PostPoneGame
    href: Application.DTOs.PostPoneGame.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch*
  commentId: Overload:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch
  href: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.html#Application_DTOs_PostPoneGame_AcceptRefusePostPoneDto_IdMatch
  name: IdMatch
  nameWithType: AcceptRefusePostPoneDto.IdMatch
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdMatch
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone*
  commentId: Overload:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone
  href: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.html#Application_DTOs_PostPoneGame_AcceptRefusePostPoneDto_StatusPostPone
  name: StatusPostPone
  nameWithType: AcceptRefusePostPoneDto.StatusPostPone
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.StatusPostPone
- uid: Domain.Enums.StatusPostPone
  commentId: T:Domain.Enums.StatusPostPone
  parent: Domain.Enums
  href: Domain.Enums.StatusPostPone.html
  name: StatusPostPone
  nameWithType: StatusPostPone
  fullName: Domain.Enums.StatusPostPone
- uid: Domain.Enums
  commentId: N:Domain.Enums
  href: Domain.html
  name: Domain.Enums
  nameWithType: Domain.Enums
  fullName: Domain.Enums
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Enums
    name: Enums
    href: Domain.Enums.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Enums
    name: Enums
    href: Domain.Enums.html
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam*
  commentId: Overload:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam
  href: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.html#Application_DTOs_PostPoneGame_AcceptRefusePostPoneDto_IdTeam
  name: IdTeam
  nameWithType: AcceptRefusePostPoneDto.IdTeam
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdTeam
- uid: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent*
  commentId: Overload:Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent
  href: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.html#Application_DTOs_PostPoneGame_AcceptRefusePostPoneDto_IdOpponent
  name: IdOpponent
  nameWithType: AcceptRefusePostPoneDto.IdOpponent
  fullName: Application.DTOs.PostPoneGame.AcceptRefusePostPoneDto.IdOpponent
