### YamlMime:ManagedReference
items:
- uid: Application.Services
  commentId: N:Application.Services
  id: Application.Services
  children:
  - Application.Services.FireBaseAuthService
  - Application.Services.FirebaseChatService
  - Application.Services.LeaderboardService
  - Application.Services.MatchInviteService
  - Application.Services.MatchMakerService
  - Application.Services.MatchService
  - Application.Services.MembershipService
  - Application.Services.PlayerAuthorizationService
  - Application.Services.PlayerService
  - Application.Services.SuperAdminService
  - Application.Services.TeamService
  langs:
  - csharp
  - vb
  name: Application.Services
  nameWithType: Application.Services
  fullName: Application.Services
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Services.FireBaseAuthService
  commentId: T:Application.Services.FireBaseAuthService
  href: Application.Services.FireBaseAuthService.html
  name: FireBaseAuthService
  nameWithType: FireBaseAuthService
  fullName: Application.Services.FireBaseAuthService
- uid: Application.Services.FirebaseChatService
  commentId: T:Application.Services.FirebaseChatService
  href: Application.Services.FirebaseChatService.html
  name: FirebaseChatService
  nameWithType: FirebaseChatService
  fullName: Application.Services.FirebaseChatService
- uid: Application.Services.LeaderboardService
  commentId: T:Application.Services.LeaderboardService
  href: Application.Services.LeaderboardService.html
  name: LeaderboardService
  nameWithType: LeaderboardService
  fullName: Application.Services.LeaderboardService
- uid: Application.Services.MatchInviteService
  commentId: T:Application.Services.MatchInviteService
  href: Application.Services.MatchInviteService.html
  name: MatchInviteService
  nameWithType: MatchInviteService
  fullName: Application.Services.MatchInviteService
- uid: Application.Services.MatchMakerService
  commentId: T:Application.Services.MatchMakerService
  href: Application.Services.MatchMakerService.html
  name: MatchMakerService
  nameWithType: MatchMakerService
  fullName: Application.Services.MatchMakerService
- uid: Application.Services.MatchService
  commentId: T:Application.Services.MatchService
  href: Application.Services.MatchService.html
  name: MatchService
  nameWithType: MatchService
  fullName: Application.Services.MatchService
- uid: Application.Services.MembershipService
  commentId: T:Application.Services.MembershipService
  href: Application.Services.MembershipService.html
  name: MembershipService
  nameWithType: MembershipService
  fullName: Application.Services.MembershipService
- uid: Application.Services.PlayerAuthorizationService
  commentId: T:Application.Services.PlayerAuthorizationService
  href: Application.Services.PlayerAuthorizationService.html
  name: PlayerAuthorizationService
  nameWithType: PlayerAuthorizationService
  fullName: Application.Services.PlayerAuthorizationService
- uid: Application.Services.PlayerService
  commentId: T:Application.Services.PlayerService
  href: Application.Services.PlayerService.html
  name: PlayerService
  nameWithType: PlayerService
  fullName: Application.Services.PlayerService
- uid: Application.Services.SuperAdminService
  commentId: T:Application.Services.SuperAdminService
  href: Application.Services.SuperAdminService.html
  name: SuperAdminService
  nameWithType: SuperAdminService
  fullName: Application.Services.SuperAdminService
- uid: Application.Services.TeamService
  commentId: T:Application.Services.TeamService
  href: Application.Services.TeamService.html
  name: TeamService
  nameWithType: TeamService
  fullName: Application.Services.TeamService
