### YamlMime:ManagedReference
items:
- uid: Application.DTOs.Filters.FilterMembershipRequestsTeam
  commentId: T:Application.DTOs.Filters.FilterMembershipRequestsTeam
  id: FilterMembershipRequestsTeam
  parent: Application.DTOs.Filters
  children:
  - Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate
  - Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate
  - Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName
  langs:
  - csharp
  - vb
  name: FilterMembershipRequestsTeam
  nameWithType: FilterMembershipRequestsTeam
  fullName: Application.DTOs.Filters.FilterMembershipRequestsTeam
  type: Class
  source:
    remote:
      path: Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: FilterMembershipRequestsTeam
    path: ../Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.DTOs.Filters
  syntax:
    content: public class FilterMembershipRequestsTeam
    content.vb: Public Class FilterMembershipRequestsTeam
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName
  commentId: P:Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName
  id: SenderName
  parent: Application.DTOs.Filters.FilterMembershipRequestsTeam
  langs:
  - csharp
  - vb
  name: SenderName
  nameWithType: FilterMembershipRequestsTeam.SenderName
  fullName: Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName
  type: Property
  source:
    remote:
      path: Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: SenderName
    path: ../Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.DTOs.Filters
  syntax:
    content: >-
      [MinLength(3)]

      [MaxLength(50)]

      public string? SenderName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <MinLength(3)>

      <MaxLength(50)>

      Public Property SenderName As String
  overload: Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName*
  attributes:
  - type: System.ComponentModel.DataAnnotations.MinLengthAttribute
    ctor: System.ComponentModel.DataAnnotations.MinLengthAttribute.#ctor(System.Int32)
    arguments:
    - type: System.Int32
      value: 3
  - type: System.ComponentModel.DataAnnotations.MaxLengthAttribute
    ctor: System.ComponentModel.DataAnnotations.MaxLengthAttribute.#ctor(System.Int32)
    arguments:
    - type: System.Int32
      value: 50
- uid: Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate
  commentId: P:Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate
  id: MinDate
  parent: Application.DTOs.Filters.FilterMembershipRequestsTeam
  langs:
  - csharp
  - vb
  name: MinDate
  nameWithType: FilterMembershipRequestsTeam.MinDate
  fullName: Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate
  type: Property
  source:
    remote:
      path: Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: MinDate
    path: ../Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
    startLine: 10
  assemblies:
  - Application
  namespace: Application.DTOs.Filters
  syntax:
    content: public DateOnly? MinDate { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.DateOnly}
    content.vb: Public Property MinDate As DateOnly?
  overload: Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate*
- uid: Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate
  commentId: P:Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate
  id: MaxDate
  parent: Application.DTOs.Filters.FilterMembershipRequestsTeam
  langs:
  - csharp
  - vb
  name: MaxDate
  nameWithType: FilterMembershipRequestsTeam.MaxDate
  fullName: Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate
  type: Property
  source:
    remote:
      path: Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: MaxDate
    path: ../Application/DTOs/Filters/FilterMembershipRequestsTeam.cs
    startLine: 12
  assemblies:
  - Application
  namespace: Application.DTOs.Filters
  syntax:
    content: public DateOnly? MaxDate { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.DateOnly}
    content.vb: Public Property MaxDate As DateOnly?
  overload: Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate*
references:
- uid: Application.DTOs.Filters
  commentId: N:Application.DTOs.Filters
  href: Application.html
  name: Application.DTOs.Filters
  nameWithType: Application.DTOs.Filters
  fullName: Application.DTOs.Filters
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.DTOs
    name: DTOs
    href: Application.DTOs.html
  - name: .
  - uid: Application.DTOs.Filters
    name: Filters
    href: Application.DTOs.Filters.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.DTOs
    name: DTOs
    href: Application.DTOs.html
  - name: .
  - uid: Application.DTOs.Filters
    name: Filters
    href: Application.DTOs.Filters.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName*
  commentId: Overload:Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName
  href: Application.DTOs.Filters.FilterMembershipRequestsTeam.html#Application_DTOs_Filters_FilterMembershipRequestsTeam_SenderName
  name: SenderName
  nameWithType: FilterMembershipRequestsTeam.SenderName
  fullName: Application.DTOs.Filters.FilterMembershipRequestsTeam.SenderName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate*
  commentId: Overload:Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate
  href: Application.DTOs.Filters.FilterMembershipRequestsTeam.html#Application_DTOs_Filters_FilterMembershipRequestsTeam_MinDate
  name: MinDate
  nameWithType: FilterMembershipRequestsTeam.MinDate
  fullName: Application.DTOs.Filters.FilterMembershipRequestsTeam.MinDate
- uid: System.Nullable{System.DateOnly}
  commentId: T:System.Nullable{System.DateOnly}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.dateonly
  name: DateOnly?
  nameWithType: DateOnly?
  fullName: System.DateOnly?
  spec.csharp:
  - uid: System.DateOnly
    name: DateOnly
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.dateonly
  - name: '?'
  spec.vb:
  - uid: System.DateOnly
    name: DateOnly
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.dateonly
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate*
  commentId: Overload:Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate
  href: Application.DTOs.Filters.FilterMembershipRequestsTeam.html#Application_DTOs_Filters_FilterMembershipRequestsTeam_MaxDate
  name: MaxDate
  nameWithType: FilterMembershipRequestsTeam.MaxDate
  fullName: Application.DTOs.Filters.FilterMembershipRequestsTeam.MaxDate
