### YamlMime:ManagedReference
items:
- uid: Application.Interfaces.Services.IChatRoomService
  commentId: T:Application.Interfaces.Services.IChatRoomService
  id: IChatRoomService
  parent: Application.Interfaces.Services
  children:
  - Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync(Application.DTOs.Chat.CreateChatRoomRequestDto,System.String)
  - Application.Interfaces.Services.IChatRoomService.CreateRoomAsync(Application.DTOs.Chat.CreateChatRoomDto,System.String)
  - Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync(System.String)
  langs:
  - csharp
  - vb
  name: IChatRoomService
  nameWithType: IChatRoomService
  fullName: Application.Interfaces.Services.IChatRoomService
  type: Interface
  source:
    remote:
      path: Application/Interfaces/Services/IChatRoomService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: IChatRoomService
    path: ../Application/Interfaces/Services/IChatRoomService.cs
    startLine: 3
  assemblies:
  - Application
  namespace: Application.Interfaces.Services
  syntax:
    content: public interface IChatRoomService
    content.vb: Public Interface IChatRoomService
- uid: Application.Interfaces.Services.IChatRoomService.CreateRoomAsync(Application.DTOs.Chat.CreateChatRoomDto,System.String)
  commentId: M:Application.Interfaces.Services.IChatRoomService.CreateRoomAsync(Application.DTOs.Chat.CreateChatRoomDto,System.String)
  id: CreateRoomAsync(Application.DTOs.Chat.CreateChatRoomDto,System.String)
  parent: Application.Interfaces.Services.IChatRoomService
  langs:
  - csharp
  - vb
  name: CreateRoomAsync(CreateChatRoomDto, string)
  nameWithType: IChatRoomService.CreateRoomAsync(CreateChatRoomDto, string)
  fullName: Application.Interfaces.Services.IChatRoomService.CreateRoomAsync(Application.DTOs.Chat.CreateChatRoomDto, string)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Services/IChatRoomService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: CreateRoomAsync
    path: ../Application/Interfaces/Services/IChatRoomService.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Interfaces.Services
  syntax:
    content: Task<string> CreateRoomAsync(CreateChatRoomDto request, string createdByUserId)
    parameters:
    - id: request
      type: Application.DTOs.Chat.CreateChatRoomDto
    - id: createdByUserId
      type: System.String
    return:
      type: System.Threading.Tasks.Task{System.String}
    content.vb: Function CreateRoomAsync(request As CreateChatRoomDto, createdByUserId As String) As Task(Of String)
  overload: Application.Interfaces.Services.IChatRoomService.CreateRoomAsync*
  nameWithType.vb: IChatRoomService.CreateRoomAsync(CreateChatRoomDto, String)
  fullName.vb: Application.Interfaces.Services.IChatRoomService.CreateRoomAsync(Application.DTOs.Chat.CreateChatRoomDto, String)
  name.vb: CreateRoomAsync(CreateChatRoomDto, String)
- uid: Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync(Application.DTOs.Chat.CreateChatRoomRequestDto,System.String)
  commentId: M:Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync(Application.DTOs.Chat.CreateChatRoomRequestDto,System.String)
  id: CreateMatchRoomAsync(Application.DTOs.Chat.CreateChatRoomRequestDto,System.String)
  parent: Application.Interfaces.Services.IChatRoomService
  langs:
  - csharp
  - vb
  name: CreateMatchRoomAsync(CreateChatRoomRequestDto, string)
  nameWithType: IChatRoomService.CreateMatchRoomAsync(CreateChatRoomRequestDto, string)
  fullName: Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync(Application.DTOs.Chat.CreateChatRoomRequestDto, string)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Services/IChatRoomService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: CreateMatchRoomAsync
    path: ../Application/Interfaces/Services/IChatRoomService.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Interfaces.Services
  syntax:
    content: Task<string> CreateMatchRoomAsync(CreateChatRoomRequestDto request, string createdByUserId)
    parameters:
    - id: request
      type: Application.DTOs.Chat.CreateChatRoomRequestDto
    - id: createdByUserId
      type: System.String
    return:
      type: System.Threading.Tasks.Task{System.String}
    content.vb: Function CreateMatchRoomAsync(request As CreateChatRoomRequestDto, createdByUserId As String) As Task(Of String)
  overload: Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync*
  nameWithType.vb: IChatRoomService.CreateMatchRoomAsync(CreateChatRoomRequestDto, String)
  fullName.vb: Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync(Application.DTOs.Chat.CreateChatRoomRequestDto, String)
  name.vb: CreateMatchRoomAsync(CreateChatRoomRequestDto, String)
- uid: Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync(System.String)
  commentId: M:Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync(System.String)
  id: GetMyRoomsAsync(System.String)
  parent: Application.Interfaces.Services.IChatRoomService
  langs:
  - csharp
  - vb
  name: GetMyRoomsAsync(string)
  nameWithType: IChatRoomService.GetMyRoomsAsync(string)
  fullName: Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync(string)
  type: Method
  source:
    remote:
      path: Application/Interfaces/Services/IChatRoomService.cs
      branch: documentacion
      repo: https://github.com/Btx69-jpg/Backend-LDS.git
    id: GetMyRoomsAsync
    path: ../Application/Interfaces/Services/IChatRoomService.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Interfaces.Services
  syntax:
    content: Task<List<ChatRoomDto>> GetMyRoomsAsync(string userId)
    parameters:
    - id: userId
      type: System.String
    return:
      type: System.Threading.Tasks.Task{System.Collections.Generic.List{Application.DTOs.Chat.ChatRoomDto}}
    content.vb: Function GetMyRoomsAsync(userId As String) As Task(Of List(Of ChatRoomDto))
  overload: Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync*
  nameWithType.vb: IChatRoomService.GetMyRoomsAsync(String)
  fullName.vb: Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync(String)
  name.vb: GetMyRoomsAsync(String)
references:
- uid: Application.Interfaces.Services
  commentId: N:Application.Interfaces.Services
  href: Application.html
  name: Application.Interfaces.Services
  nameWithType: Application.Interfaces.Services
  fullName: Application.Interfaces.Services
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Services
    name: Services
    href: Application.Interfaces.Services.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Services
    name: Services
    href: Application.Interfaces.Services.html
- uid: Application.Interfaces.Services.IChatRoomService.CreateRoomAsync*
  commentId: Overload:Application.Interfaces.Services.IChatRoomService.CreateRoomAsync
  href: Application.Interfaces.Services.IChatRoomService.html#Application_Interfaces_Services_IChatRoomService_CreateRoomAsync_Application_DTOs_Chat_CreateChatRoomDto_System_String_
  name: CreateRoomAsync
  nameWithType: IChatRoomService.CreateRoomAsync
  fullName: Application.Interfaces.Services.IChatRoomService.CreateRoomAsync
- uid: Application.DTOs.Chat.CreateChatRoomDto
  commentId: T:Application.DTOs.Chat.CreateChatRoomDto
  parent: Application.DTOs.Chat
  href: Application.DTOs.Chat.CreateChatRoomDto.html
  name: CreateChatRoomDto
  nameWithType: CreateChatRoomDto
  fullName: Application.DTOs.Chat.CreateChatRoomDto
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Threading.Tasks.Task{System.String}
  commentId: T:System.Threading.Tasks.Task{System.String}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<string>
  nameWithType: Task<string>
  fullName: System.Threading.Tasks.Task<string>
  nameWithType.vb: Task(Of String)
  fullName.vb: System.Threading.Tasks.Task(Of String)
  name.vb: Task(Of String)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Application.DTOs.Chat
  commentId: N:Application.DTOs.Chat
  href: Application.html
  name: Application.DTOs.Chat
  nameWithType: Application.DTOs.Chat
  fullName: Application.DTOs.Chat
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.DTOs
    name: DTOs
    href: Application.DTOs.html
  - name: .
  - uid: Application.DTOs.Chat
    name: Chat
    href: Application.DTOs.Chat.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.DTOs
    name: DTOs
    href: Application.DTOs.html
  - name: .
  - uid: Application.DTOs.Chat
    name: Chat
    href: Application.DTOs.Chat.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync*
  commentId: Overload:Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync
  href: Application.Interfaces.Services.IChatRoomService.html#Application_Interfaces_Services_IChatRoomService_CreateMatchRoomAsync_Application_DTOs_Chat_CreateChatRoomRequestDto_System_String_
  name: CreateMatchRoomAsync
  nameWithType: IChatRoomService.CreateMatchRoomAsync
  fullName: Application.Interfaces.Services.IChatRoomService.CreateMatchRoomAsync
- uid: Application.DTOs.Chat.CreateChatRoomRequestDto
  commentId: T:Application.DTOs.Chat.CreateChatRoomRequestDto
  parent: Application.DTOs.Chat
  href: Application.DTOs.Chat.CreateChatRoomRequestDto.html
  name: CreateChatRoomRequestDto
  nameWithType: CreateChatRoomRequestDto
  fullName: Application.DTOs.Chat.CreateChatRoomRequestDto
- uid: Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync*
  commentId: Overload:Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync
  href: Application.Interfaces.Services.IChatRoomService.html#Application_Interfaces_Services_IChatRoomService_GetMyRoomsAsync_System_String_
  name: GetMyRoomsAsync
  nameWithType: IChatRoomService.GetMyRoomsAsync
  fullName: Application.Interfaces.Services.IChatRoomService.GetMyRoomsAsync
- uid: System.Threading.Tasks.Task{System.Collections.Generic.List{Application.DTOs.Chat.ChatRoomDto}}
  commentId: T:System.Threading.Tasks.Task{System.Collections.Generic.List{Application.DTOs.Chat.ChatRoomDto}}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<List<ChatRoomDto>>
  nameWithType: Task<List<ChatRoomDto>>
  fullName: System.Threading.Tasks.Task<System.Collections.Generic.List<Application.DTOs.Chat.ChatRoomDto>>
  nameWithType.vb: Task(Of List(Of ChatRoomDto))
  fullName.vb: System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of Application.DTOs.Chat.ChatRoomDto))
  name.vb: Task(Of List(Of ChatRoomDto))
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Application.DTOs.Chat.ChatRoomDto
    name: ChatRoomDto
    href: Application.DTOs.Chat.ChatRoomDto.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Application.DTOs.Chat.ChatRoomDto
    name: ChatRoomDto
    href: Application.DTOs.Chat.ChatRoomDto.html
  - name: )
  - name: )
