### YamlMime:ManagedReference
items:
- uid: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests
  commentId: N:Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests
  id: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests
  children:
  - Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.ManagerRankMatchMakerManagerServiceTests
  - Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.MatchMakerServiceTests
  langs:
  - csharp
  - vb
  name: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests
  nameWithType: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests
  fullName: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests
  type: Namespace
  assemblies:
  - Tests
references:
- uid: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.ManagerRankMatchMakerManagerServiceTests
  commentId: T:Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.ManagerRankMatchMakerManagerServiceTests
  href: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.ManagerRankMatchMakerManagerServiceTests.html
  name: ManagerRankMatchMakerManagerServiceTests
  nameWithType: ManagerRankMatchMakerManagerServiceTests
  fullName: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.ManagerRankMatchMakerManagerServiceTests
- uid: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.MatchMakerServiceTests
  commentId: T:Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.MatchMakerServiceTests
  href: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.MatchMakerServiceTests.html
  name: MatchMakerServiceTests
  nameWithType: MatchMakerServiceTests
  fullName: Tests.Unit.ApplicationTests.ServicesTests.HubsTests.RankMatchMakerTests.MatchMakerServiceTests
